Add E2E test for puppet android app
posix4e/puppet pull request #27
Opened 2023-08-04 17:41 UTC by vkolgi

Adds github action workflow to run tests against trigger.
Adds test case to run tests against sauce labs.
Adds necessary boilerplate code to setup test execution.

2023-08-04 18:28 UTC, posix4e requested changes
Amazing work and very close

- can you make sure the black linter runs across the whole of the python codebase?
- All these sleeps are harsh. We should come up with a plan with hopefully less sleeps. But for now it's fine.

2023-08-04 18:28 UTC, posix4e commented on e2e_tests/test_sauce_labs.py
> +        import time
I don't like mid file imports make sure to run black and import sort on this file

2023-08-04 18:53 UTC, posix4e commented
@vkola

2023-08-04 18:53 UTC, closed without merging

2023-08-05 10:29 UTC, vkolgi commented
Agree with the explicit sleeps. 
They are specifically used in the context where we come back from the android settings page to the app.
Sane approach is to bring forward the Chatter activity, than pressing back button twice.
However, activity to foreground didn't work for Real android device in Saucelabs but worked for the emulator on my local machine. So had to resort to this. With some checks in place, we should be able to avoid those explicit sleeps.

2023-08-05 11:34 UTC, posix4e commented
Got it